export default {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  DELETE_USER : "DELETE_USER",
  GET_ERRORS: "GET_ERRORS",
  ADD_NEW_CAMP: "ADD_NEW_CAMP",
  DELETE_CAMP : "DELETE_CAMP",
  UPDATE_CAMP : "UPDATE_CAMP",
  FINAL_UPDATE_CAMP : "FINAL_UPDATE_CAMP",
};
